### ISSUE TITLE
Планируется реализация такого?

### ISSUE THREAD

**Issue by MEFRREEX** [qPexLegendary/DGuard-Nukkit#4]
Мне понравился ваш плагин и его реализация, единственное, хотелось бы узнать, сможете в ближайших обновлениях реализовать флаг разрешающий/запрещающий ломать блоки в регионе и возможность создания "региона в регионе"? (это будет полезно для создания региона с пвп ареной и т.д. в регионе спавна)
Надеюсь на дальнейшее развитие плагина!

**Comment by ScarletRedMan** [comment]
Здравствуйте. Хорошо, я сделаю на днях реализацию данного флага в плагине. А вот насчет создания регионов внутри регионов в ближайшее время не планируется.

**Comment by MEFRREEX** [comment]
Понял, спасибо за ответ!
