### ISSUE TITLE
А как загрузить плагин на хостинг?

### ISSUE THREAD

**Issue by Flainyrs** [qPexLegendary/DGuard-Nukkit#7]
**Как загрузить плагин на хостинг ?**

**Comment by Flainyrs** [comment]
Как его сделать в phar расширение?

**Comment by Flainyrs** [comment]
Случайно:D

**Comment by Flainyrs** [comment]
я закидываю папку DGuard в папку plugins но, ничего не происходит нужен phar файл

**Comment by qPexLegendary** [comment]
Скачай DevTools, установи его, далее в папку plugins помещаешь папку DGuard

**Comment by ScarletRedMan** [comment]
В разделе Releases размещены релизы версий плагина. Там все есть.
https://github.com/qPexLegendary/DGuard-Nukkit/releases/tag/2.2

**Comment by ScarletRedMan** [comment]
Это плагин для Nukkit, не PMMP! Читаем внимательно описание репозитория!
